spring:
  datasource:
    url: jdbc:mysql://localhost/basic_db
    username: root
    password: 123456
  jpa:    hibernate:      ddl-auto: update
  data:
    web:
      pageable:
        one-indexed-parameters: true